### import liberaries

In [1]:
import pandas as pd 
import numpy as np

### read the data

In [3]:
data = pd.read_csv("Global Superstore.csv",encoding='latin1')

In [5]:
data.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical

#### Exploratory Data Analysis

In [7]:
data.size

1230960

In [9]:
data.shape

(51290, 24)

In [13]:
data.columns

Index(['Row_ID', 'Order_ID', 'Order_Date', 'Ship_Date', 'Ship_Mode',
       'Customer_ID', 'Customer_Name', 'Segment', 'City', 'State', 'Country',
       'Postal_Code', 'Market', 'Region', 'Product_ID', 'Category',
       'Sub_Category', 'Product_Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping_Cost', 'Order_Priority'],
      dtype='object')

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row_ID          51290 non-null  int64
 1   Order_ID        51290 non-null  object
 2   Order_Date      51290 non-null  object
 3   Ship_Date       51290 non-null  object
 4   Ship_Mode       51290 non-null  object
 5   Customer_ID     51290 non-null  object
 6   Customer_Name   51290 non-null  object
 7   Segment         51290 non-null  object
 8   City            51290 non-null  object
 9   State           51290 non-null  object
 10  Country         51290 non-null  object
 11  Postal_Code     9994 non-null   float64
 12  Market          51290 non-null  object
 13  Region          51290 non-null  object
 14  Product_ID      51290 non-null  object
 15  Category        51290 non-null  object
 16  Sub_Category    51290 non-null  object
 17  Product_Name    51290 non-null  object
 18  Sales           51290 non-null  float64
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  float64
 22  Shipping_Cost   51290 non-null  float64
 23  Order_Priority  51290 non-null  object
dtypes: float64(5), int64(2), object(17)
memory usage: 9.4+ MB

In [11]:
data.describe()

,Row_ID,Postal_Code,Sales,Quantity,Discount,Profit,Shipping_Cost
count,51290.00000,9994.000000,51290.000000,51290.000000,51290.000000,51290.000000,51290.000000
mean,25645.50000,55190.379428,246.490581,3.476545,0.142908,28.610982,26.375818
std,14806.29199,32063.693350,487.565361,2.278766,0.212280,174.340972,57.296810
min,1.00000,1040.000000,0.444000,1.000000,0.000000,-6599.978000,0.002000
25%,12823.25000,23223.000000,30.758625,2.000000,0.000000,0.000000,2.610000
50%,25645.50000,56430.500000,85.053000,3.000000,0.000000,9.240000,7.790000
75%,38467.75000,90008.000000,251.053200,5.000000,0.200000,36.810000,24.450000
max,51290.00000,99301.000000,22638.480000,14.000000,0.850000,8399.976000,933.570000

In [12]:
data.describe(include=object)

,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,Country,Market,Region,Product_ID,Category,Sub_Category,Product_Name,Order_Priority
count,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290
unique,25035,1430,1464,4,1590,795,3,3636,1094,147,7,13,10292,3,17,3788,4
top,CA-2014-100111,2014-06-18,2014-11-22,Standard Class,PO-18850,Muhammed Yedwab,Consumer,New York City,California,United States,APAC,Central,OFF-AR-10003651,Office Supplies,Binders,Staples,Medium
freq,14,135,130,30775,97,108,26518,915,2001,9994,11002,11117,35,31273,6152,227,29433

In [13]:
data.corr(numeric_only=True)

,Row_ID,Postal_Code,Sales,Quantity,Discount,Profit,Shipping_Cost
Row_ID,1.000000,0.009671,-0.043889,-0.173483,0.087594,-0.019037,-0.039076
Postal_Code,0.009671,1.000000,-0.023854,0.012761,0.058443,-0.029961,-0.025449
Sales,-0.043889,-0.023854,1.000000,0.313577,-0.086722,0.484918,0.768073
Quantity,-0.173483,0.012761,0.313577,1.000000,-0.019875,0.104365,0.272649
Discount,0.087594,0.058443,-0.086722,-0.019875,1.000000,-0.316490,-0.079055
Profit,-0.019037,-0.029961,0.484918,0.104365,-0.316490,1.000000,0.354441
Shipping_Cost,-0.039076,-0.025449,0.768073,0.272649,-0.079055,0.354441,1.000000

### Missing data

In [15]:
data.isnull().sum()

Row_ID                0
Order_ID              0
Order_Date            0
Ship_Date             0
Ship_Mode             0
Customer_ID           0
Customer_Name         0
Segment               0
City                  0
State                 0
Country               0
Postal_Code       41296
Market                0
Region                0
Product_ID            0
Category              0
Sub_Category          0
Product_Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
Shipping_Cost         0
Order_Priority        0
dtype: int64

### Duplicate Data

In [17]:
data.duplicated().sum()

0

### Select a Certain column

In [23]:
data['Sales'] # series

0        2309.650
1        3709.395
2        5175.171
3        2892.510
4        2832.960
           ...
51285      65.100
51286       0.444
51287      22.920
51288      13.440
51289      61.380
Name: Sales, Length: 51290, dtype: float64

In [27]:
# select profit 
data['Profit']

0        762.1845
1       -288.7650
2        919.9710
3        -96.5400
4        311.5200
           ...
51285      4.5000
51286     -1.1100
51287     11.2308
51288      2.4000
51289      1.8000
Name: Profit, Length: 51290, dtype: float64

In [28]:
### Selecting a Dataframe 
data[['Category']].head()

     Category
0  Technology
1   Furniture
2  Technology
3  Technology
4  Technology

In [32]:
type(data[['Category']])

pandas.core.frame.DataFrame

In [33]:
data.columns

Index(['Row_ID', 'Order_ID', 'Order_Date', 'Ship_Date', 'Ship_Mode',
       'Customer_ID', 'Customer_Name', 'Segment', 'City', 'State', 'Country',
       'Postal_Code', 'Market', 'Region', 'Product_ID', 'Category',
       'Sub_Category', 'Product_Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping_Cost', 'Order_Priority'],
      dtype='object')

### Selecting multiple columns

In [36]:
# Return - Order_id , order_date , customer_id and customer name , sales ,profit , quantity 
data[['Order_ID' , 'Order_Date', 'Customer_ID', 'Customer_Name' , 'Sales','Profit','Quantity']].head(1)

,Order_ID,Order_Date,Customer_ID,Customer_Name,Sales,Profit,Quantity
0,CA-2012-124891,2012-07-31,RH-19495,Rick Hansen,2309.65,762.1845,7

In [38]:
data[['Category' , 'Sub_Category', 'Sales', 'Profit' ]].head(2)

     Category Sub_Category     Sales    Profit
0  Technology  Accessories  2309.650  762.1845
1   Furniture       Chairs  3709.395 -288.7650

### Filteration on Dataframes 
##### Syntax - dataframe[condition]

In [42]:
# Q1. Return the orders where sales is greater than 15000
data[data['Sales'] > 15000]

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
329,38123,CA-2013-118689,2013-10-03,2013-10-10,Standard Class,TC-20980,Tamara Chand,Corporate,Lafayette,Indiana,...,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.95,5,0.0,8399.9760,349.0700,Medium
12887,33994,CA-2011-145317,2011-03-18,2011-03-23,Standard Class,SM-20320,Sean Miller,Home Office,Jacksonville,Florida,...,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.48,6,0.5,-1811.0784,24.2865,Medium

In [44]:
## Q2. Profit is more than 5k 
data[data['Profit'] > 5000]

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
290,35487,CA-2014-166709,2014-11-18,2014-11-23,Standard Class,HL-15040,Hunter Lopez,Consumer,Newark,Delaware,...,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.97,3,0.0,5039.9856,363.19000,Medium
329,38123,CA-2013-118689,2013-10-03,2013-10-10,Standard Class,TC-20980,Tamara Chand,Corporate,Lafayette,Indiana,...,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.95,5,0.0,8399.9760,349.07000,Medium
14843,39450,CA-2014-140151,2014-03-24,2014-03-26,First Class,RB-19360,Raymond Buch,Consumer,Seattle,Washington,...,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.96,4,0.0,6719.9808,20.00054,Medium

In [47]:
### Q3. Profit is negative 
data[data['Profit']<0].head(3)

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
9,40936,CA-2012-116638,2012-01-28,2012-01-31,Second Class,JH-15985,Joseph Holt,Consumer,Concord,North Carolina,...,FUR-TA-10000198,Furniture,Tables,Chromcraft Bull-Nose Wood Oval Conference Tabl...,4297.644,13,0.4,-1862.3124,865.74,Critical

### Category Filteration

In [50]:
### Q4. Orders with category as technology 
data[data['Category'] == 'Technology'].head(2)

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium

###  Q5. Orders from India country
### Q6. Orders from Canada market 
### Q7. Orders from consumer segement 
### Q8. Orders from High priority 
### Q9. Order from paris city 
### Q10. Orders where Quantity is more than 8

#### Filteration on Multiple Conditions

In [56]:
### Q11. Orders from Furniture with sales more than 5k 
data[(data['Category'] == 'Furniture') & (data['Sales'] > 5000 )].head(2)

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
7,31192,IN-2012-86369,2012-04-14,2012-04-18,Standard Class,MB-18085,Mick Brown,Consumer,Hamilton,Waikato,...,FUR-TA-10002958,Furniture,Tables,"Chromcraft Conference Table, Fully Assembled",5244.84,6,0.0,996.48,878.38,High
42,25795,IN-2014-76016,2014-09-26,2014-09-28,Second Class,VG-21805,Vivek Grady,Corporate,Thiruvananthapuram,Kerala,...,FUR-BO-10004852,Furniture,Bookcases,"Sauder Classic Bookcase, Traditional",5667.87,13,0.0,2097.03,658.35,Medium

In [58]:
### or - | 
#### Q12. Order with either from technology or from furniture 
data[ ( data['Category'] == 'Technology') | ( data['Category'] == 'Furniture') ]

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51239,34383,CA-2014-118773,2014-02-10,2014-02-15,Standard Class,TP-21415,Tom Prescott,Consumer,Houston,Texas,...,FUR-FU-10000550,Furniture,Furnishings,Stacking Trays by OIC,3.984,2,0.6,-2.6892,0.05,Medium
51242,36409,CA-2012-153073,2012-11-13,2012-11-13,Same Day,HA-14905,Helen Abelman,Consumer,Chicago,Illinois,...,FUR-FU-10001025,Furniture,Furnishings,"Eldon Imàge Series Desk Accessories, Clear",17.496,9,0.6,-7.4358,0.05,Medium
51246,44081,TU-2013-7830,2013-06-14,2013-06-18,Standard Class,LW-6990,Lindsay Williams,Corporate,Kayseri,Kayseri,...,FUR-ADV-10002329,Furniture,Furnishings,"Advantus Light Bulb, Erganomic",7.476,1,0.6,-9.5340,0.05,Medium
51254,31608,CA-2013-142902,2013-09-13,2013-09-15,Second Class,BP-11185,Ben Peterman,Corporate,Arvada,Colorado,...,FUR-FU-10001756,Furniture,Furnishings,"Eldon Expressions Desk Accessory, Wood Photo F...",15.232,1,0.2,1.7136,0.04,High
51259,39396,CA-2013-169663,2013-03-11,2013-03-14,First Class,RH-19510,Rick Huthwaite,Home Office,Los Angeles,California,...,TEC-AC-10003038,Technology,Accessories,Kingston Digital DataTraveler 16GB USB 2.0,26.850,3,0.0,5.1015,0.04,Medium

In [59]:
### Not operator - ~ 
#### Q13. Orders which are not greater than 0 profit 
data[ ~(data['Profit'] > 0 )]

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.630,Critical
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.160,Medium
9,40936,CA-2012-116638,2012-01-28,2012-01-31,Second Class,JH-15985,Joseph Holt,Consumer,Concord,North Carolina,...,FUR-TA-10000198,Furniture,Tables,Chromcraft Bull-Nose Wood Oval Conference Tabl...,4297.644,13,0.4,-1862.3124,865.740,Critical
30,220,US-2011-128776,2011-12-28,2011-12-30,Second Class,RR-19525,Rick Reed,Corporate,Santo Domingo,Santo Domingo,...,TEC-PH-10002815,Technology,Phones,"Samsung Smart Phone, VoIP",1696.640,5,0.2,-148.4600,704.056,Critical
32,32735,CA-2012-139731,2012-10-15,2012-10-15,Same Day,JE-15745,Joel Eaton,Consumer,Amarillo,Texas,...,FUR-CH-10002024,Furniture,Chairs,HON 5400 Series Task Chairs for Big and Tall,2453.430,5,0.3,-350.4900,690.420,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51276,31558,US-2014-155299,2014-06-09,2014-06-13,Standard Class,Dl-13600,Dorris liebe,Corporate,Pasadena,Texas,...,OFF-AP-10002203,Office Supplies,Appliances,Eureka Disposable Bags for Sanitaire Vibra Gro...,1.624,2,0.8,-4.4660,0.020,Medium
51278,43818,NI-2011-4700,2011-09-08,2011-09-10,Second Class,PO-8865,Patrick O'Donnell,Consumer,Lagos,Lagos,...,OFF-STA-10001791,Office Supplies,Art,"Stanley Highlighters, Water Color",5.364,1,0.7,-6.4560,0.020,High
51279,46231,ZI-2011-4350,2011-03-21,2011-03-26,Standard Class,AS-285,Alejandro Savely,Corporate,Harare,Harare,...,OFF-SAN-10001862,Office Supplies,Art,"Sanford Highlighters, Easy-Erase",9.612,2,0.7,-21.1680,0.020,Medium
51280,46582,TU-2014-6730,2014-11-29,2014-11-30,First Class,KF-6285,Karen Ferguson,Home Office,Midyat,Mardin,...,OFF-BOS-10000350,Office Supplies,Art,"Boston Pens, Blue",34.128,6,0.6,-49.5720,0.020,Medium
51286,35398,US-2014-102288,2014-06-20,2014-06-24,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,Houston,Texas,...,OFF-AP-10002906,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444,1,0.8,-1.1100,0.010,Medium

In [60]:
### Q14. Except APAC continent - return all orders 
### Q15. Orders with profit more than 2k and sales more than 5k
### Q16. Orders that are from France and China 
### Q17. Order that are from technology having sales more than 10000 and from china 
### Q18. Orders from India - Mumbai

In [62]:
data[~(data['Market'] == 'APAC' )]

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.570,Critical
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.160,Medium
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.040,Critical
8,40155,CA-2014-135909,2014-10-14,2014-10-21,Standard Class,JW-15220,Jane Waco,Corporate,Sacramento,California,...,OFF-BI-10003527,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,5083.960,5,0.2,1906.4850,867.690,Low
9,40936,CA-2012-116638,2012-01-28,2012-01-31,Second Class,JH-15985,Joseph Holt,Consumer,Concord,North Carolina,...,FUR-TA-10000198,Furniture,Tables,Chromcraft Bull-Nose Wood Oval Conference Tabl...,4297.644,13,0.4,-1862.3124,865.740,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51282,9922,MX-2012-100258,2012-12-28,2012-12-31,First Class,KM-16375,Katherine Murray,Home Office,Managua,Managua,...,OFF-PA-10004020,Office Supplies,Paper,"SanDisk Message Books, 8.5 x 11",18.640,1,0.0,8.0000,0.010,Medium
51286,35398,US-2014-102288,2014-06-20,2014-06-24,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,Houston,Texas,...,OFF-AP-10002906,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444,1,0.8,-1.1100,0.010,Medium
51287,40470,US-2013-155768,2013-12-02,2013-12-02,Same Day,LB-16795,Laurel Beltran,Home Office,Oxnard,California,...,OFF-EN-10001219,Office Supplies,Envelopes,"#10- 4 1/8"" x 9 1/2"" Security-Tint Envelopes",22.920,3,0.0,11.2308,0.010,High
51288,9596,MX-2012-140767,2012-02-18,2012-02-22,Standard Class,RB-19795,Ross Baird,Home Office,Valinhos,São Paulo,...,OFF-BI-10000806,Office Supplies,Binders,"Acco Index Tab, Economy",13.440,2,0.0,2.4000,0.003,Medium
51289,6147,MX-2012-134460,2012-05-22,2012-05-26,Second Class,MC-18100,Mick Crebagga,Consumer,Tipitapa,Managua,...,OFF-PA-10004155,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.380,3,0.0,1.8000,0.002,High

In [63]:
### isin() - for using multiple values from a single cateogry
### between( ) - range filteration

In [65]:
### Q19. Orders from India and china 
data[ data['Country'].isin(['India','China'])].head(1)

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
14,27704,IN-2013-73951,2013-06-06,2013-06-08,Second Class,PF-19120,Peter Fuller,Consumer,Mudanjiang,Heilongjiang,...,OFF-AP-10003500,Office Supplies,Appliances,"KitchenAid Microwave, White",3701.52,12,0.0,1036.08,804.54,Critical

In [68]:
#### Q20. Orders which has sales from 4000 - 5000 
data[data['Sales'].between(4000, 5000)].head(2)

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
9,40936,CA-2012-116638,2012-01-28,2012-01-31,Second Class,JH-15985,Joseph Holt,Consumer,Concord,North Carolina,...,FUR-TA-10000198,Furniture,Tables,Chromcraft Bull-Nose Wood Oval Conference Tabl...,4297.644,13,0.4,-1862.3124,865.74,Critical
10,34577,CA-2011-102988,2011-04-05,2011-04-09,Second Class,GM-14695,Greg Maxwell,Corporate,Alexandria,Virginia,...,OFF-SU-10002881,Office Supplies,Supplies,Martin Yale Chadless Opener Electric Letter Op...,4164.050,5,0.0,83.2810,846.54,High

In [71]:
#### Q.21 Orders which has disocount between (0.2 , 0.4 )
#### Q.22 Orders with profit from 3000 - 5000 
#### Q.23 Orders with profit - 2000 - 6000 and sales between 5000 - 10000
#### Q24. Orders from copiers , machines and chairs and phones 
#### Q25. Orders from Mexico , Australia and Germany and iraq

#### Category Data Analysis 
###### unique() , nunique() , value_counts()

In [76]:
# Category - 
data['Category'].unique()   # returns all the unique elements

array(['Technology', 'Furniture', 'Office Supplies'], dtype=object)

In [77]:
data['Category'].nunique()   # number of Unique values

3

In [78]:
data['Category'].value_counts()

Category
Office Supplies    31273
Technology         10141
Furniture           9876
Name: count, dtype: int64

In [82]:
### Q.26 cateogorical Analysis on - segment , country , sub category , city , order priority

In [83]:
data['Market'].unique()

array(['US', 'APAC', 'EU', 'Africa', 'EMEA', 'LATAM', 'Canada'],
      dtype=object)

In [86]:
data['Market'].nunique()

7

In [87]:
data['Market'].value_counts()

Market
APAC      11002
LATAM     10294
EU        10000
US         9994
EMEA       5029
Africa     4587
Canada      384
Name: count, dtype: int64

#### loc and iloc - Indexing 
- loc - Label Based Indexing
- syntax df.loc[row_index,columns_index]

- iloc - Number based indexing
- syntax - df.iloc[row_index,column_index]

In [91]:
user = pd.DataFrame({ 'ID' : [ 1,2,3,4,5,6] , 
                    'Name' : ['Amay','Sakshi','Viraj','Mohini','ravi' ,'vinita'],
                     'salary' : [ 23000,34000,12000,45000,67000,90000],
                     'age' : [ 23,24,26,19,20,21],
                     'job' : [ 'DA' , 'DS', 'MLE', 'DA','MLOPS' ,'DS'] ,
                     'city' : [ 'Pune' , 'Hyd' ,'Ban' ,'Pune' , 'Delhi' ,'Pune']})

In [93]:
user.head(2)

   ID    Name  salary  age job  city
0   1    Amay   23000   23  DA  Pune
1   2  Sakshi   34000   24  DS   Hyd

##### loc[row_start : row_stop ,column_start: column_stop]

In [96]:
user.loc[3:5]   # Row filterations

   ID    Name  salary  age    job   city
3   4  Mohini   45000   19     DA   Pune
4   5    ravi   67000   20  MLOPS  Delhi
5   6  vinita   90000   21     DS   Pune

In [98]:
user.loc[1:2,['Name','city']]

     Name city
1  Sakshi  Hyd
2   Viraj  Ban

In [100]:
user.loc[ : , 'Name']

0      Amay
1    Sakshi
2     Viraj
3    Mohini
4      ravi
5    vinita
Name: Name, dtype: object

#### loc - Label based indexer

In [103]:
data.loc[:]   # all data

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.570,Critical
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.630,Critical
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.490,Medium
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.160,Medium
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.040,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,29002,IN-2014-62366,2014-06-19,2014-06-19,Same Day,KE-16420,Katrina Edelman,Corporate,Kure,Hiroshima,...,OFF-FA-10000746,Office Supplies,Fasteners,"Advantus Thumb Tacks, 12 Pack",65.100,5,0.0,4.5000,0.010,Medium
51286,35398,US-2014-102288,2014-06-20,2014-06-24,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,Houston,Texas,...,OFF-AP-10002906,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444,1,0.8,-1.1100,0.010,Medium
51287,40470,US-2013-155768,2013-12-02,2013-12-02,Same Day,LB-16795,Laurel Beltran,Home Office,Oxnard,California,...,OFF-EN-10001219,Office Supplies,Envelopes,"#10- 4 1/8"" x 9 1/2"" Security-Tint Envelopes",22.920,3,0.0,11.2308,0.010,High
51288,9596,MX-2012-140767,2012-02-18,2012-02-22,Standard Class,RB-19795,Ross Baird,Home Office,Valinhos,São Paulo,...,OFF-BI-10000806,Office Supplies,Binders,"Acco Index Tab, Economy",13.440,2,0.0,2.4000,0.003,Medium
51289,6147,MX-2012-134460,2012-05-22,2012-05-26,Second Class,MC-18100,Mick Crebagga,Consumer,Tipitapa,Managua,...,OFF-PA-10004155,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.380,3,0.0,1.8000,0.002,High

In [105]:
data.loc[0:9 , ['Customer_ID' , 'Sales']]

  Customer_ID     Sales
0    RH-19495  2309.650
1    JR-16210  3709.395
2    CR-12730  5175.171
3    KM-16375  2892.510
4     RH-9495  2832.960
5    JM-15655  2862.675
6    TS-21340  1822.080
7    MB-18085  5244.840
8    JW-15220  5083.960
9    JH-15985  4297.644

In [107]:
data.loc[ data['Sales'] > 10000 , ['Customer_Name' , 'Sales' , 'Profit'] ]

      Customer_Name      Sales     Profit
290    Hunter Lopez  10499.970  5039.9856
329    Tamara Chand  17499.950  8399.9760
7399   Tom Ashbrook  11199.968  3919.9888
12887   Sean Miller  22638.480 -1811.0784
14843  Raymond Buch  13999.960  6719.9808

In [109]:
data['Profit_status'] = "loss/Profit"

In [111]:
data['Profit_status']

0        loss/Profit
1        loss/Profit
2        loss/Profit
3        loss/Profit
4        loss/Profit
            ...
51285    loss/Profit
51286    loss/Profit
51287    loss/Profit
51288    loss/Profit
51289    loss/Profit
Name: Profit_status, Length: 51290, dtype: object

In [ ]:
data.loc[ data['Profit'] < 0 , data['Profit_status'] ] = "Loss" 
data.loc[data['Profit'] > 0 , data['Profit_status']] = "Profit"

In [ ]:
data['Profit_status']

#### iloc - Number based Indexer

In [16]:
data.iloc[0]   # first row returns

Row_ID                                                        32298
Order_ID                                             CA-2012-124891
Order_Date                                               2012-07-31
Ship_Date                                                2012-07-31
Ship_Mode                                                  Same Day
Customer_ID                                                RH-19495
Customer_Name                                           Rick Hansen
Segment                                                    Consumer
City                                                  New York City
State                                                      New York
Country                                               United States
Postal_Code                                                 10024.0
Market                                                           US
Region                                                         East
Product_ID                                          TEC-AC-10003033
Category                                                 Technology
Sub_Category                                            Accessories
Product_Name      Plantronics CS510 - Over-the-Head monaural Wir...
Sales                                                       2309.65
Quantity                                                          7
Discount                                                        0.0
Profit                                                     762.1845
Shipping_Cost                                                933.57
Order_Priority                                             Critical
Name: 0, dtype: object

In [18]:
data.iloc[:5]   # top 5 rows

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical

In [22]:
data.iloc[ [45,500,3400,2300,5600 ]]   ### specific rows

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
45,35395,CA-2011-116904,2011-09-23,2011-09-28,Standard Class,SC-20095,Sanjit Chand,Consumer,Minneapolis,Minnesota,...,OFF-BI-10001120,Office Supplies,Binders,Ibico EPK-21 Electric Binding System,9449.950,5,0.0,4630.4755,655.610,Medium
500,9435,MX-2014-139164,2014-09-08,2014-09-11,First Class,SF-20200,Sarah Foster,Consumer,Antiguo Cuscatlán,La Libertad,...,TEC-PH-10000018,Technology,Phones,"Nokia Smart Phone, Full Size",1274.700,3,0.0,293.1600,290.523,Critical
3400,34925,CA-2011-169726,2011-08-09,2011-08-13,Standard Class,JH-15985,Joseph Holt,Consumer,Seattle,Washington,...,OFF-BI-10004600,Office Supplies,Binders,Ibico Ibimaster 300 Manual Binding System,2060.744,7,0.2,643.9825,90.470,Medium
2300,36193,CA-2013-135776,2013-12-24,2013-12-31,Standard Class,EH-13765,Edward Hooks,Corporate,Seattle,Washington,...,OFF-ST-10003470,Office Supplies,Storage,"Tennsco Snap-Together Open Shelving Units, Sta...",1117.920,4,0.0,55.8960,122.230,Low
5600,44194,TU-2014-3610,2014-12-29,2015-01-01,First Class,JD-5895,Jonathan Doherty,Corporate,Mamak,Ankara,...,OFF-HOO-10004910,Office Supplies,Appliances,"Hoover Refrigerator, White",209.760,1,0.6,-209.7600,60.040,Critical

In [24]:
data.columns

Index(['Row_ID', 'Order_ID', 'Order_Date', 'Ship_Date', 'Ship_Mode',
       'Customer_ID', 'Customer_Name', 'Segment', 'City', 'State', 'Country',
       'Postal_Code', 'Market', 'Region', 'Product_ID', 'Category',
       'Sub_Category', 'Product_Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping_Cost', 'Order_Priority'],
      dtype='object')

In [30]:
# data.iloc[ rows , columns ] 
data.iloc[ 5 , 6]

'Jim Mitchum'

In [32]:
## data.iloc[ row_start : row_stop , col_start : col_stop ] 
# all data return cust_id , name , sales , profit 
data.iloc[ : , [ 5 ,6 ,18 , 21 ] ]

      Customer_ID     Customer_Name     Sales    Profit
0        RH-19495       Rick Hansen  2309.650  762.1845
1        JR-16210     Justin Ritter  3709.395 -288.7650
2        CR-12730      Craig Reiter  5175.171  919.9710
3        KM-16375  Katherine Murray  2892.510  -96.5400
4         RH-9495       Rick Hansen  2832.960  311.5200
...           ...               ...       ...       ...
51285    KE-16420   Katrina Edelman    65.100    4.5000
51286    ZC-21910  Zuschuss Carroll     0.444   -1.1100
51287    LB-16795    Laurel Beltran    22.920   11.2308
51288    RB-19795        Ross Baird    13.440    2.4000
51289    MC-18100     Mick Crebagga    61.380    1.8000

[51290 rows x 4 columns]

#### Sorting In dataframe 
- sort_values("column")

In [41]:
data.sort_values("Sales") # default - asc

       Row_ID        Order_ID  Order_Date   Ship_Date       Ship_Mode  \
51286   35398  US-2014-102288  2014-06-20  2014-06-24  Standard Class
51194   40589  CA-2014-124114  2014-03-03  2014-03-03        Same Day
51223   39955  CA-2013-168361  2013-06-22  2013-06-26  Standard Class
51138   36008  CA-2011-112403  2011-03-31  2011-03-31        Same Day
51166   33403  US-2011-152723  2011-09-26  2011-09-26        Same Day
...       ...             ...         ...         ...             ...
290     35487  CA-2014-166709  2014-11-18  2014-11-23  Standard Class
7399    33920  CA-2014-127180  2014-10-23  2014-10-25     First Class
14843   39450  CA-2014-140151  2014-03-24  2014-03-26     First Class
329     38123  CA-2013-118689  2013-10-03  2013-10-10  Standard Class
12887   33994  CA-2011-145317  2011-03-18  2011-03-23  Standard Class

      Customer_ID     Customer_Name      Segment           City         State  \
51286    ZC-21910  Zuschuss Carroll     Consumer        Houston         Texas
51194    RS-19765    Roland Schwarz    Corporate           Waco         Texas
51223    KB-16600       Ken Brennan    Corporate        Chicago      Illinois
51138    JO-15280     Jas O'Carroll     Consumer   Philadelphia  Pennsylvania
51166    HG-14965     Henry Goldwyn    Corporate       Mesquite         Texas
...           ...               ...          ...            ...           ...
290      HL-15040      Hunter Lopez     Consumer         Newark      Delaware
7399     TA-21385      Tom Ashbrook  Home Office  New York City      New York
14843    RB-19360      Raymond Buch     Consumer        Seattle    Washington
329      TC-20980      Tamara Chand    Corporate      Lafayette       Indiana
12887    SM-20320       Sean Miller  Home Office   Jacksonville       Florida

       ...       Product_ID         Category Sub_Category  \
51286  ...  OFF-AP-10002906  Office Supplies   Appliances
51194  ...  OFF-BI-10004022  Office Supplies      Binders
51223  ...  OFF-BI-10003727  Office Supplies      Binders
51138  ...  OFF-BI-10003529  Office Supplies      Binders
51166  ...  OFF-BI-10003460  Office Supplies      Binders
...    ...              ...              ...          ...
290    ...  TEC-CO-10004722       Technology      Copiers
7399   ...  TEC-CO-10004722       Technology      Copiers
14843  ...  TEC-CO-10004722       Technology      Copiers
329    ...  TEC-CO-10004722       Technology      Copiers
12887  ...  TEC-MA-10002412       Technology     Machines

                                            Product_Name      Sales Quantity  \
51286  Hoover Replacement Belt for Commercial Guardsm...      0.444        1
51194           Acco Suede Grain Vinyl Round Ring Binder      0.556        1
51223  Avery Durable Slant Ring Binders With Label Ho...      0.836        1
51138                      Avery Round Ring Poly Binders      0.852        1
51166                                  Acco 3-Hole Punch      0.876        1
...                                                  ...        ...      ...
290                Canon imageCLASS 2200 Advanced Copier  10499.970        3
7399               Canon imageCLASS 2200 Advanced Copier  11199.968        4
14843              Canon imageCLASS 2200 Advanced Copier  13999.960        4
329                Canon imageCLASS 2200 Advanced Copier  17499.950        5
12887  Cisco TelePresence System EX90 Videoconferenci...  22638.480        6

      Discount     Profit  Shipping_Cost  Order_Priority
51286      0.8    -1.1100        0.01000          Medium
51194      0.8    -0.9452        0.08000          Medium
51223      0.8    -1.3376        0.06000          Medium
51138      0.7    -0.5964        0.10000            High
51166      0.8    -1.4016        0.09000            High
...        ...        ...            ...             ...
290        0.0  5039.9856      363.19000          Medium
7399       0.2  3919.9888       45.98000            High
14843      0.0  6719.9808       20.00054          Medium
329        0.0  8399.9760      349.07000          Medium
12887      0.5 -1811.0784       24.28650          Medium

[51290 rows x 24 columns]

In [43]:
data.sort_values('Sales' , ascending= False).head(5)

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
12887,33994,CA-2011-145317,2011-03-18,2011-03-23,Standard Class,SM-20320,Sean Miller,Home Office,Jacksonville,Florida,...,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480,6,0.5,-1811.0784,24.28650,Medium
329,38123,CA-2013-118689,2013-10-03,2013-10-10,Standard Class,TC-20980,Tamara Chand,Corporate,Lafayette,Indiana,...,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760,349.07000,Medium
14843,39450,CA-2014-140151,2014-03-24,2014-03-26,First Class,RB-19360,Raymond Buch,Consumer,Seattle,Washington,...,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808,20.00054,Medium
7399,33920,CA-2014-127180,2014-10-23,2014-10-25,First Class,TA-21385,Tom Ashbrook,Home Office,New York City,New York,...,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968,4,0.2,3919.9888,45.98000,High
290,35487,CA-2014-166709,2014-11-18,2014-11-23,Standard Class,HL-15040,Hunter Lopez,Consumer,Newark,Delaware,...,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856,363.19000,Medium

In [45]:
## Top 10 orders by profit 
data.sort_values('Profit' , ascending=False).head(10)

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
329,38123,CA-2013-118689,2013-10-03,2013-10-10,Standard Class,TC-20980,Tamara Chand,Corporate,Lafayette,Indiana,...,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760,349.07000,Medium
14843,39450,CA-2014-140151,2014-03-24,2014-03-26,First Class,RB-19360,Raymond Buch,Consumer,Seattle,Washington,...,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808,20.00054,Medium
290,35487,CA-2014-166709,2014-11-18,2014-11-23,Standard Class,HL-15040,Hunter Lopez,Consumer,Newark,Delaware,...,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856,363.19000,Medium
122,40336,CA-2013-117121,2013-12-18,2013-12-22,Standard Class,AB-10105,Adrian Barton,Consumer,Detroit,Michigan,...,OFF-BI-10000545,Office Supplies,Binders,GBC Ibimaster 500 Manual ProClick Binding System,9892.740,13,0.0,4946.3700,498.70000,Medium
45,35395,CA-2011-116904,2011-09-23,2011-09-28,Standard Class,SC-20095,Sanjit Chand,Consumer,Minneapolis,Minnesota,...,OFF-BI-10001120,Office Supplies,Binders,Ibico EPK-21 Electric Binding System,9449.950,5,0.0,4630.4755,655.61000,Medium
17,12069,ES-2014-1651774,2014-09-08,2014-09-14,Standard Class,PJ-18835,Patrick Jones,Corporate,Prato,Tuscany,...,OFF-AP-10004512,Office Supplies,Appliances,"Hoover Stove, Red",7958.580,14,0.0,3979.0800,778.32000,Low
7399,33920,CA-2014-127180,2014-10-23,2014-10-25,First Class,TA-21385,Tom Ashbrook,Home Office,New York City,New York,...,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968,4,0.2,3919.9888,45.98000,High
76,31806,CA-2012-145352,2012-03-16,2012-03-22,Standard Class,CM-12385,Christopher Martinez,Consumer,Atlanta,Georgia,...,OFF-BI-10003527,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,6354.950,5,0.0,3177.4750,581.12000,Medium
215,27720,ID-2011-64599,2011-02-10,2011-02-15,Standard Class,CA-11965,Carol Adams,Corporate,Fuji,Shizuoka,...,TEC-PH-10000303,Technology,Phones,"Samsung Smart Phone, VoIP",6998.640,11,0.0,2939.3100,413.80000,Medium
313,23212,IN-2013-50809,2013-06-12,2013-06-17,Standard Class,CA-12775,Cynthia Arntzen,Consumer,Kota,Chhattisgarh,...,TEC-PH-10000169,Technology,Phones,"Apple Smart Phone, with Caller ID",5751.540,9,0.0,2817.9900,353.85000,Medium

In [49]:
# text sorting 
data.sort_values('City')

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
46395,14865,ES-2012-3346363,2012-11-13,2012-11-14,First Class,TS-21655,Trudy Schmidt,Consumer,Aachen,North Rhine-Westphalia,...,OFF-BI-10003152,Office Supplies,Binders,"Avery Hole Reinforcements, Recycled",9.540,2,0.0,4.080,0.990,High
43544,18870,ES-2012-1706068,2012-11-10,2012-11-14,Standard Class,MO-17500,Mary O'Rourke,Consumer,Aachen,North Rhine-Westphalia,...,OFF-AR-10000659,Office Supplies,Art,"BIC Pencil Sharpener, Fluorescent",60.540,2,0.0,20.580,1.500,High
1053,18868,ES-2012-1706068,2012-11-10,2012-11-14,Standard Class,MO-17500,Mary O'Rourke,Consumer,Aachen,North Rhine-Westphalia,...,OFF-ST-10000288,Office Supplies,Storage,"Fellowes Lockers, Industrial",1309.203,7,0.1,494.403,197.030,High
30414,14866,ES-2012-3346363,2012-11-13,2012-11-14,First Class,TS-21655,Trudy Schmidt,Consumer,Aachen,North Rhine-Westphalia,...,OFF-FA-10004139,Office Supplies,Fasteners,"Advantus Thumb Tacks, 12 Pack",26.040,2,0.0,1.020,5.310,High
13594,18871,ES-2012-1706068,2012-11-10,2012-11-14,Standard Class,MO-17500,Mary O'Rourke,Consumer,Aachen,North Rhine-Westphalia,...,OFF-AR-10003629,Office Supplies,Art,"Boston Canvas, Water Color",170.460,3,0.0,25.560,22.560,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27079,41916,SF-2011-5640,2011-08-20,2011-08-23,First Class,KH-6690,Kristen Hastings,Corporate,eMbalenhle,Mpumalanga,...,OFF-FIS-10003463,Office Supplies,Supplies,"Fiskars Letter Opener, Easy Grip",59.100,2,0.0,7.080,6.940,Medium
15773,5711,MX-2014-123274,2014-03-07,2014-03-12,Second Class,LC-17050,Liz Carlisle,Consumer,Águas Lindas de Goiás,Goiás,...,OFF-SU-10004361,Office Supplies,Supplies,"Kleencut Trimmer, High Speed",110.480,4,0.0,22.080,18.354,Medium
33824,5580,MX-2013-138828,2013-12-20,2013-12-21,First Class,KB-16405,Katrina Bavinger,Home Office,Águas Lindas de Goiás,Goiás,...,OFF-LA-10004239,Office Supplies,Labels,"Smead Color Coded Labels, Adjustable",14.600,2,0.0,3.920,3.971,High
35813,6908,MX-2014-140207,2014-03-13,2014-03-18,Standard Class,CM-12115,Chad McGuire,Consumer,Águas Lindas de Goiás,Goiás,...,OFF-BI-10000335,Office Supplies,Binders,"Cardinal 3-Hole Punch, Durable",40.400,2,0.0,9.280,3.349,Medium
42637,5712,MX-2014-123274,2014-03-07,2014-03-12,Second Class,LC-17050,Liz Carlisle,Consumer,Águas Lindas de Goiás,Goiás,...,OFF-FA-10003929,Office Supplies,Fasteners,"Accos Rubber Bands, 12 Pack",21.480,2,0.0,5.760,1.681,Medium

In [ ]:
### Sort the data by country 
### Sort the data by customer names

In [51]:
### Date sorting - 
data.sort_values('Order_Date')

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
25084,48883,HU-2011-1220,2011-01-01,2011-01-05,Second Class,AT-735,Annie Thurman,Consumer,Budapest,Budapest,...,OFF-TEN-10001585,Office Supplies,Storage,"Tenex Box, Single Width",66.1200,4,0.00,29.6400,8.170,High
22951,22253,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,JH-15985,Joseph Holt,Consumer,Wagga Wagga,New South Wales,...,OFF-SU-10000618,Office Supplies,Supplies,"Acme Trimmer, High Speed",120.3660,3,0.10,36.0360,9.720,Medium
9352,42433,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,TB-11280,Toby Braunhardt,Consumer,Constantine,Constantine,...,OFF-TEN-10000025,Office Supplies,Storage,"Tenex Lockers, Blue",408.3000,2,0.00,106.1400,35.460,Medium
42055,22254,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,JH-15985,Joseph Holt,Consumer,Wagga Wagga,New South Wales,...,OFF-PA-10001968,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",55.2420,2,0.10,15.3420,1.800,Medium
31579,11731,IT-2011-3647632,2011-01-01,2011-01-05,Second Class,EM-14140,Eugene Moren,Home Office,Stockholm,Stockholm,...,OFF-PA-10001492,Office Supplies,Paper,"Enermax Note Cards, Premium",44.8650,3,0.50,-26.0550,4.820,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50052,8857,MX-2014-110527,2014-12-31,2015-01-02,Second Class,CM-12190,Charlotte Melton,Consumer,Managua,Managua,...,OFF-LA-10004182,Office Supplies,Labels,"Hon Color Coded Labels, 5000 Label Set",26.4000,3,0.00,12.3600,0.350,Medium
3590,26333,IN-2014-30390,2014-12-31,2015-01-03,First Class,JD-16150,Justin Deggeller,Corporate,Bangkok,Bangkok,...,FUR-TA-10001531,Furniture,Tables,"Lesro Training Table, Adjustable Height",1048.7313,9,0.57,-1195.2387,86.860,High
28699,50446,TZ-2014-8350,2014-12-31,2015-01-03,First Class,JA-5970,Joseph Airdo,Consumer,Dar es Salaam,Dar Es Salaam,...,OFF-FEL-10001792,Office Supplies,Storage,"Fellowes Folders, Wire Frame",22.9230,1,0.10,4.0530,6.110,High
29674,8856,MX-2014-110527,2014-12-31,2015-01-02,Second Class,CM-12190,Charlotte Melton,Consumer,Managua,Managua,...,OFF-SU-10001624,Office Supplies,Supplies,"Kleencut Ruler, High Speed",72.3200,8,0.00,6.4000,5.639,Medium
35641,41743,TU-2014-5170,2014-12-31,2015-01-04,Second Class,VD-11670,Valerie Dominguez,Consumer,Konya,Konya,...,TEC-SAN-10004215,Technology,Accessories,"SanDisk Keyboard, Bluetooth",32.5920,1,0.60,-25.2780,3.400,Medium

### Sorting on multiple columns

In [58]:
data.sort_values(['Customer_Name','Sales','Profit'],ascending=[False,False,False])

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
4507,11670,IT-2012-4926272,2012-08-17,2012-08-22,Standard Class,ZD-21925,Zuschuss Donatelli,Consumer,Berlin,Berlin,...,FUR-CH-10002782,Furniture,Chairs,"Office Star Executive Leather Armchair, Adjust...",1127.8080,3,0.20,-126.8820,72.710,Medium
4495,18672,ES-2011-4052630,2011-02-21,2011-02-26,Standard Class,ZD-21925,Zuschuss Donatelli,Consumer,Milan,Lombardy,...,FUR-TA-10003899,Furniture,Tables,"Barricks Round Table, with Bottom Storage",1003.0200,4,0.50,-942.9000,72.920,Medium
4861,6369,MX-2013-141698,2013-04-24,2013-04-29,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,Rondonópolis,Mato Grosso,...,TEC-PH-10002867,Technology,Phones,"Cisco Smart Phone, with Caller ID",872.3200,2,0.00,8.7200,68.222,High
4750,35111,CA-2013-152471,2013-07-09,2013-07-09,Same Day,ZD-21925,Zuschuss Donatelli,Consumer,Jacksonville,Florida,...,TEC-PH-10002824,Technology,Phones,Jabra SPEAK 410 Multidevice Speakerphone,823.9600,5,0.20,51.4975,69.660,Medium
3668,18446,IT-2012-2197138,2012-07-13,2012-07-17,Standard Class,ZD-21925,Zuschuss Donatelli,Consumer,Marignane,Provence-Alpes-Côte d'Azur,...,TEC-CO-10002686,Technology,Copiers,"Hewlett Fax Machine, Laser",815.7960,3,0.15,-95.9940,85.360,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50695,24468,IN-2013-37803,2013-06-25,2013-06-29,Standard Class,AB-10015,Aaron Bergman,Consumer,Mackay,Queensland,...,OFF-BI-10000106,Office Supplies,Binders,"Cardinal Hole Reinforcements, Clear",12.9600,3,0.10,3.4200,0.220,High
46552,39519,CA-2011-152905,2011-02-19,2011-02-25,Standard Class,AB-10015,Aaron Bergman,Consumer,Arlington,Texas,...,OFF-ST-10000321,Office Supplies,Storage,Akro Stacking Bins,12.6240,2,0.20,-2.5248,0.970,Low
49219,12157,ES-2014-1181938,2014-02-12,2014-02-16,Standard Class,AB-10015,Aaron Bergman,Consumer,Vincennes,Ile-de-France,...,OFF-BI-10000312,Office Supplies,Binders,"Cardinal Binder Covers, Economy",12.0000,1,0.00,0.4800,0.510,Medium
49563,46917,IR-2012-1280,2012-07-17,2012-07-19,First Class,AB-15,Aaron Bergman,Consumer,Qom,Qom,...,OFF-WIL-10000986,Office Supplies,Binders,"Wilson Jones Binder Covers, Economy",11.1900,1,0.00,2.8800,0.450,Medium
49844,26084,ID-2014-48583,2014-06-23,2014-06-27,Second Class,AB-10015,Aaron Bergman,Consumer,Palembang,Sumatera Selatan,...,OFF-LA-10000732,Office Supplies,Labels,"Novimex Round Labels, 5000 Label Set",10.5894,3,0.47,-3.2706,0.390,Medium

#### Grouping of cateogries
- Aggregates you have to call 
- groupby('cateogry')

In [78]:
tot_cat_sales = data.groupby('Category')['Sales'].sum()
tot_cat_profit = data.groupby('Category')['Profit'].sum()

In [76]:
tot_cat_sales

Category
Furniture          4.110874e+06
Office Supplies    3.787070e+06
Technology         4.744557e+06
Name: Sales, dtype: float64

In [80]:
tot_cat_profit

Category
Furniture          285204.72380
Office Supplies    518473.83430
Technology         663778.73318
Name: Profit, dtype: float64

In [ ]:
### Q1 Avg profit per category 
### Q2. Lowest sales per subcategory 
### Q3. Max profit per subcategory 
### Q4. Avg sales per subcategory 
### Q5. Order priority wise order counts 
### Q6 order shipent wise order counts

In [100]:
data.groupby('Ship_Mode')['Order_ID'].count().sort_values(ascending=False)

Ship_Mode
Standard Class    30775
Second Class      10309
First Class        7505
Same Day           2701
Name: Order_ID, dtype: int64

In [82]:
data.groupby('Category')['Profit'].mean()

Category
Furniture          28.878567
Office Supplies    16.578961
Technology         65.454958
Name: Profit, dtype: float64

In [86]:
data.groupby('Sub_Category')['Sales'].min()

Sub_Category
Accessories     0.990
Appliances      0.444
Art             1.344
Binders         0.556
Bookcases      35.490
Chairs         13.545
Copiers        35.460
Envelopes       1.632
Fasteners       1.240
Furnishings     1.892
Labels          1.668
Machines       11.511
Paper           3.380
Phones          2.970
Storage         2.799
Supplies        1.744
Tables         24.368
Name: Sales, dtype: float64

In [88]:
### Grouping one column with Multiple Aggregates -
data.groupby('Segment')['Sales'].agg(['sum','mean','min','max','count'])

                      sum        mean    min       max  count
Segment
Consumer     6.507949e+06  245.416299  0.444  13999.96  26518
Corporate    3.824698e+06  247.890176  0.556  17499.95  15429
Home Office  2.309855e+06  247.228403  0.990  22638.48   9343

In [ ]:
### Q1. Top 5 Countries with highest avg_profit 
### Q2. Top 5 cities with Highest avg_sales 
### Q3. Top 5 Customers with Highest_orders 
### Q4. Top 5 customers with Highest sales - sum
### Q5. Top 5 Customers with Highest Profit - sum

In [108]:
data.groupby('Customer_Name')['Order_ID'].count().sort_values(ascending=False).head(5)

Customer_Name
Muhammed Yedwab    108
Steven Ward        106
Gary Hwang         102
Patrick O'Brill    102
Bill Eplett        102
Name: Order_ID, dtype: int64

### Grouping with Many categories

In [115]:
### category with segment - grouping 
data.groupby(['Category','Segment'])['Sales'].mean()

Category         Segment
Furniture        Consumer       417.742054
                 Corporate      419.548702
                 Home Office    406.315015
Office Supplies  Consumer       120.891192
                 Corporate      121.997691
                 Home Office    120.210179
Technology       Consumer       460.364190
                 Corporate      464.697265
                 Home Office    494.898862
Name: Sales, dtype: float64

In [119]:
### category wise Market - Avg sales 
data.groupby(['Category','Market'])['Sales'].mean().reset_index()   # reset_index - dataframe

           Category  Market       Sales
0         Furniture    APAC  553.286978
1         Furniture  Africa  308.479612
2         Furniture  Canada  252.268571
3         Furniture    EMEA  296.910047
4         Furniture      EU  519.055996
5         Furniture   LATAM  340.877674
6         Furniture      US  349.834887
7   Office Supplies    APAC  143.163321
8   Office Supplies  Africa   87.604444
9   Office Supplies  Canada  108.426282
10  Office Supplies    EMEA   83.920531
11  Office Supplies      EU  158.796027
12  Office Supplies   LATAM   96.199374
13  Office Supplies      US  119.324101
14       Technology    APAC  566.565203
15       Technology  Africa  353.860640
16       Technology  Canada  404.597077
17       Technology    EMEA  312.738652
18       Technology      EU  582.554444
19       Technology   LATAM  384.738446
20       Technology      US  452.709276

### Data Type Conversion 
- astype(datatype)  - int , float , string
- to_numeric() 
- to_datetime()

In [154]:
data.dtypes.reset_index()

             index        0
0           Row_ID    int64
1         Order_ID   object
2       Order_Date   object
3        Ship_Date   object
4        Ship_Mode   object
5      Customer_ID   object
6    Customer_Name   object
7          Segment   object
8             City   object
9            State   object
10         Country   object
11     Postal_Code  float64
12          Market   object
13          Region   object
14      Product_ID   object
15        Category   object
16    Sub_Category   object
17    Product_Name   object
18           Sales    int32
19        Quantity    int64
20        Discount  float64
21          Profit  float64
22   Shipping_Cost  float64
23  Order_Priority   object

In [156]:
### Conversion of Sales into int 
data['Sales'] = data['Sales'].astype(int)

In [132]:
data['Sales'].dtype

dtype('int32')

In [143]:
### postal code to str 
data['Postal_Code'] = data['Postal_Code'].astype(float)

In [145]:
data['Postal_Code'].dtype

dtype('float64')

In [164]:
#### Order_Date - date 
data['Order_Date'] = pd.to_datetime(data['Order_Date'])

In [ ]:
data['Order_Date'].dt.month

In [ ]:
data['Order_Date'].dt.day

In [170]:
data['Order_Date'].dt.year

0        2012
1        2013
2        2013
3        2013
4        2013
         ...
51285    2014
51286    2014
51287    2013
51288    2012
51289    2012
Name: Order_Date, Length: 51290, dtype: int32

In [172]:
data['Year'] = data['Order_Date'].dt.year
data['Month'] = data['Order_Date'].dt.month
data['Day'] = data['Order_Date'].dt.day

In [174]:
data[['Year','Month','Day']]

       Year  Month  Day
0      2012      7   31
1      2013      2    5
2      2013     10   17
3      2013      1   28
4      2013     11    5
...     ...    ...  ...
51285  2014      6   19
51286  2014      6   20
51287  2013     12    2
51288  2012      2   18
51289  2012      5   22

[51290 rows x 3 columns]