### import liberaries

In [5]:
import pandas as pd 
import numpy as np

### read the data

In [19]:
data = pd.read_csv("Global Superstore.csv",encoding='latin1')

In [21]:
data.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical

#### Exploratory Data Analysis

In [24]:
data.size

1230960

In [26]:
data.shape

(51290, 24)

In [28]:
data.columns

Index(['Row_ID', 'Order_ID', 'Order_Date', 'Ship_Date', 'Ship_Mode',
       'Customer_ID', 'Customer_Name', 'Segment', 'City', 'State', 'Country',
       'Postal_Code', 'Market', 'Region', 'Product_ID', 'Category',
       'Sub_Category', 'Product_Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping_Cost', 'Order_Priority'],
      dtype='object')

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row_ID          51290 non-null  int64
 1   Order_ID        51290 non-null  object
 2   Order_Date      51290 non-null  object
 3   Ship_Date       51290 non-null  object
 4   Ship_Mode       51290 non-null  object
 5   Customer_ID     51290 non-null  object
 6   Customer_Name   51290 non-null  object
 7   Segment         51290 non-null  object
 8   City            51290 non-null  object
 9   State           51290 non-null  object
 10  Country         51290 non-null  object
 11  Postal_Code     9994 non-null   float64
 12  Market          51290 non-null  object
 13  Region          51290 non-null  object
 14  Product_ID      51290 non-null  object
 15  Category        51290 non-null  object
 16  Sub_Category    51290 non-null  object
 17  Product_Name    51290 non-null  object
 18  Sales           51290 non-null  float64
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  float64
 22  Shipping_Cost   51290 non-null  float64
 23  Order_Priority  51290 non-null  object
dtypes: float64(5), int64(2), object(17)
memory usage: 9.4+ MB

In [32]:
data.describe()

,Row_ID,Postal_Code,Sales,Quantity,Discount,Profit,Shipping_Cost
count,51290.00000,9994.000000,51290.000000,51290.000000,51290.000000,51290.000000,51290.000000
mean,25645.50000,55190.379428,246.490581,3.476545,0.142908,28.610982,26.375818
std,14806.29199,32063.693350,487.565361,2.278766,0.212280,174.340972,57.296810
min,1.00000,1040.000000,0.444000,1.000000,0.000000,-6599.978000,0.002000
25%,12823.25000,23223.000000,30.758625,2.000000,0.000000,0.000000,2.610000
50%,25645.50000,56430.500000,85.053000,3.000000,0.000000,9.240000,7.790000
75%,38467.75000,90008.000000,251.053200,5.000000,0.200000,36.810000,24.450000
max,51290.00000,99301.000000,22638.480000,14.000000,0.850000,8399.976000,933.570000

In [34]:
data.describe(include=object)

,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,Country,Market,Region,Product_ID,Category,Sub_Category,Product_Name,Order_Priority
count,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290
unique,25035,1430,1464,4,1590,795,3,3636,1094,147,7,13,10292,3,17,3788,4
top,CA-2014-100111,2014-06-18,2014-11-22,Standard Class,PO-18850,Muhammed Yedwab,Consumer,New York City,California,United States,APAC,Central,OFF-AR-10003651,Office Supplies,Binders,Staples,Medium
freq,14,135,130,30775,97,108,26518,915,2001,9994,11002,11117,35,31273,6152,227,29433

In [36]:
data.corr(numeric_only=True)

,Row_ID,Postal_Code,Sales,Quantity,Discount,Profit,Shipping_Cost
Row_ID,1.000000,0.009671,-0.043889,-0.173483,0.087594,-0.019037,-0.039076
Postal_Code,0.009671,1.000000,-0.023854,0.012761,0.058443,-0.029961,-0.025449
Sales,-0.043889,-0.023854,1.000000,0.313577,-0.086722,0.484918,0.768073
Quantity,-0.173483,0.012761,0.313577,1.000000,-0.019875,0.104365,0.272649
Discount,0.087594,0.058443,-0.086722,-0.019875,1.000000,-0.316490,-0.079055
Profit,-0.019037,-0.029961,0.484918,0.104365,-0.316490,1.000000,0.354441
Shipping_Cost,-0.039076,-0.025449,0.768073,0.272649,-0.079055,0.354441,1.000000

### Missing data

In [39]:
data.isnull().sum()

Row_ID                0
Order_ID              0
Order_Date            0
Ship_Date             0
Ship_Mode             0
Customer_ID           0
Customer_Name         0
Segment               0
City                  0
State                 0
Country               0
Postal_Code       41296
Market                0
Region                0
Product_ID            0
Category              0
Sub_Category          0
Product_Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
Shipping_Cost         0
Order_Priority        0
dtype: int64

### Duplicate Data

In [42]:
data.duplicated().sum()

0

### Select a Certain column

In [57]:
data['Sales'] # series

0        2309.650
1        3709.395
2        5175.171
3        2892.510
4        2832.960
           ...
51285      65.100
51286       0.444
51287      22.920
51288      13.440
51289      61.380
Name: Sales, Length: 51290, dtype: float64

In [59]:
# select profit 
data['Profit']

0        762.1845
1       -288.7650
2        919.9710
3        -96.5400
4        311.5200
           ...
51285      4.5000
51286     -1.1100
51287     11.2308
51288      2.4000
51289      1.8000
Name: Profit, Length: 51290, dtype: float64

In [69]:
### Selecting a Dataframe 
data[['Category']].head()

     Category
0  Technology
1   Furniture
2  Technology
3  Technology
4  Technology

In [75]:
type(data[['Category']])

pandas.core.frame.DataFrame

In [80]:
data.columns

Index(['Row_ID', 'Order_ID', 'Order_Date', 'Ship_Date', 'Ship_Mode',
       'Customer_ID', 'Customer_Name', 'Segment', 'City', 'State', 'Country',
       'Postal_Code', 'Market', 'Region', 'Product_ID', 'Category',
       'Sub_Category', 'Product_Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping_Cost', 'Order_Priority'],
      dtype='object')

### Selecting multiple columns

In [92]:
# Return - Order_id , order_date , customer_id and customer name , sales ,profit , quantity 
data[['Order_ID' , 'Order_Date', 'Customer_ID', 'Customer_Name' , 'Sales','Profit','Quantity']].head(1)

,Order_ID,Order_Date,Customer_ID,Customer_Name,Sales,Profit,Quantity
0,CA-2012-124891,2012-07-31,RH-19495,Rick Hansen,2309.65,762.1845,7

In [94]:
data[['Category' , 'Sub_Category', 'Sales', 'Profit' ]].head(2)

     Category Sub_Category     Sales    Profit
0  Technology  Accessories  2309.650  762.1845
1   Furniture       Chairs  3709.395 -288.7650

### Filteration on Dataframes 
##### Syntax - dataframe[condition]

In [111]:
# Q1. Return the orders where sales is greater than 15000
data[data['Sales'] > 15000]

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
329,38123,CA-2013-118689,2013-10-03,2013-10-10,Standard Class,TC-20980,Tamara Chand,Corporate,Lafayette,Indiana,...,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.95,5,0.0,8399.9760,349.0700,Medium
12887,33994,CA-2011-145317,2011-03-18,2011-03-23,Standard Class,SM-20320,Sean Miller,Home Office,Jacksonville,Florida,...,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.48,6,0.5,-1811.0784,24.2865,Medium

In [113]:
## Q2. Profit is more than 5k 
data[data['Profit'] > 5000]

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
290,35487,CA-2014-166709,2014-11-18,2014-11-23,Standard Class,HL-15040,Hunter Lopez,Consumer,Newark,Delaware,...,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.97,3,0.0,5039.9856,363.19000,Medium
329,38123,CA-2013-118689,2013-10-03,2013-10-10,Standard Class,TC-20980,Tamara Chand,Corporate,Lafayette,Indiana,...,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.95,5,0.0,8399.9760,349.07000,Medium
14843,39450,CA-2014-140151,2014-03-24,2014-03-26,First Class,RB-19360,Raymond Buch,Consumer,Seattle,Washington,...,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.96,4,0.0,6719.9808,20.00054,Medium

In [119]:
### Q3. Profit is negative 
data[data['Profit']<0].head(3)

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
9,40936,CA-2012-116638,2012-01-28,2012-01-31,Second Class,JH-15985,Joseph Holt,Consumer,Concord,North Carolina,...,FUR-TA-10000198,Furniture,Tables,Chromcraft Bull-Nose Wood Oval Conference Tabl...,4297.644,13,0.4,-1862.3124,865.74,Critical

### Category Filteration

In [126]:
### Q4. Orders with category as technology 
data[data['Category'] == 'Technology'].head(2)

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium

###  Q5. Orders from India country
### Q6. Orders from Canada market 
### Q7. Orders from consumer segement 
### Q8. Orders from High priority 
### Q9. Order from paris city 
### Q10. Orders where Quantity is more than 8

#### Filteration on Multiple Conditions

In [144]:
### Q11. Orders from Furniture with sales more than 5k 
data[(data['Category'] == 'Furniture') & (data['Sales'] > 5000 )].head(2)

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
7,31192,IN-2012-86369,2012-04-14,2012-04-18,Standard Class,MB-18085,Mick Brown,Consumer,Hamilton,Waikato,...,FUR-TA-10002958,Furniture,Tables,"Chromcraft Conference Table, Fully Assembled",5244.84,6,0.0,996.48,878.38,High
42,25795,IN-2014-76016,2014-09-26,2014-09-28,Second Class,VG-21805,Vivek Grady,Corporate,Thiruvananthapuram,Kerala,...,FUR-BO-10004852,Furniture,Bookcases,"Sauder Classic Bookcase, Traditional",5667.87,13,0.0,2097.03,658.35,Medium

In [146]:
### or - | 
#### Q12. Order with either from technology or from furniture 
data[ ( data['Category'] == 'Technology') | ( data['Category'] == 'Furniture') ]

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51239,34383,CA-2014-118773,2014-02-10,2014-02-15,Standard Class,TP-21415,Tom Prescott,Consumer,Houston,Texas,...,FUR-FU-10000550,Furniture,Furnishings,Stacking Trays by OIC,3.984,2,0.6,-2.6892,0.05,Medium
51242,36409,CA-2012-153073,2012-11-13,2012-11-13,Same Day,HA-14905,Helen Abelman,Consumer,Chicago,Illinois,...,FUR-FU-10001025,Furniture,Furnishings,"Eldon Imàge Series Desk Accessories, Clear",17.496,9,0.6,-7.4358,0.05,Medium
51246,44081,TU-2013-7830,2013-06-14,2013-06-18,Standard Class,LW-6990,Lindsay Williams,Corporate,Kayseri,Kayseri,...,FUR-ADV-10002329,Furniture,Furnishings,"Advantus Light Bulb, Erganomic",7.476,1,0.6,-9.5340,0.05,Medium
51254,31608,CA-2013-142902,2013-09-13,2013-09-15,Second Class,BP-11185,Ben Peterman,Corporate,Arvada,Colorado,...,FUR-FU-10001756,Furniture,Furnishings,"Eldon Expressions Desk Accessory, Wood Photo F...",15.232,1,0.2,1.7136,0.04,High
51259,39396,CA-2013-169663,2013-03-11,2013-03-14,First Class,RH-19510,Rick Huthwaite,Home Office,Los Angeles,California,...,TEC-AC-10003038,Technology,Accessories,Kingston Digital DataTraveler 16GB USB 2.0,26.850,3,0.0,5.1015,0.04,Medium

In [148]:
### Not operator - ~ 
#### Q13. Orders which are not greater than 0 profit 
data[ ~(data['Profit'] > 0 )]

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.630,Critical
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.160,Medium
9,40936,CA-2012-116638,2012-01-28,2012-01-31,Second Class,JH-15985,Joseph Holt,Consumer,Concord,North Carolina,...,FUR-TA-10000198,Furniture,Tables,Chromcraft Bull-Nose Wood Oval Conference Tabl...,4297.644,13,0.4,-1862.3124,865.740,Critical
30,220,US-2011-128776,2011-12-28,2011-12-30,Second Class,RR-19525,Rick Reed,Corporate,Santo Domingo,Santo Domingo,...,TEC-PH-10002815,Technology,Phones,"Samsung Smart Phone, VoIP",1696.640,5,0.2,-148.4600,704.056,Critical
32,32735,CA-2012-139731,2012-10-15,2012-10-15,Same Day,JE-15745,Joel Eaton,Consumer,Amarillo,Texas,...,FUR-CH-10002024,Furniture,Chairs,HON 5400 Series Task Chairs for Big and Tall,2453.430,5,0.3,-350.4900,690.420,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51276,31558,US-2014-155299,2014-06-09,2014-06-13,Standard Class,Dl-13600,Dorris liebe,Corporate,Pasadena,Texas,...,OFF-AP-10002203,Office Supplies,Appliances,Eureka Disposable Bags for Sanitaire Vibra Gro...,1.624,2,0.8,-4.4660,0.020,Medium
51278,43818,NI-2011-4700,2011-09-08,2011-09-10,Second Class,PO-8865,Patrick O'Donnell,Consumer,Lagos,Lagos,...,OFF-STA-10001791,Office Supplies,Art,"Stanley Highlighters, Water Color",5.364,1,0.7,-6.4560,0.020,High
51279,46231,ZI-2011-4350,2011-03-21,2011-03-26,Standard Class,AS-285,Alejandro Savely,Corporate,Harare,Harare,...,OFF-SAN-10001862,Office Supplies,Art,"Sanford Highlighters, Easy-Erase",9.612,2,0.7,-21.1680,0.020,Medium
51280,46582,TU-2014-6730,2014-11-29,2014-11-30,First Class,KF-6285,Karen Ferguson,Home Office,Midyat,Mardin,...,OFF-BOS-10000350,Office Supplies,Art,"Boston Pens, Blue",34.128,6,0.6,-49.5720,0.020,Medium
51286,35398,US-2014-102288,2014-06-20,2014-06-24,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,Houston,Texas,...,OFF-AP-10002906,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444,1,0.8,-1.1100,0.010,Medium

In [ ]:
### Q14. Except APAC continent - return all orders 
### Q15. Orders with profit more than 2k and sales more than 5k
### Q16. Orders that are from France and China 
### Q17. Order that are from technology having sales more than 10000 and from china 
### Q18. Orders from India - Mumbai

In [ ]:
### isin() - for using multiple values from a single cateogry
### between( ) - range filteration

In [153]:
### Q19. Orders from India and china 
data[ data['Country'].isin(['India','China'])].head(1)

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
14,27704,IN-2013-73951,2013-06-06,2013-06-08,Second Class,PF-19120,Peter Fuller,Consumer,Mudanjiang,Heilongjiang,...,OFF-AP-10003500,Office Supplies,Appliances,"KitchenAid Microwave, White",3701.52,12,0.0,1036.08,804.54,Critical

In [158]:
#### Q20. Orders which has sales from 4000 - 5000 
data[data['Sales'].between(4000, 5000)].head(2)

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority
9,40936,CA-2012-116638,2012-01-28,2012-01-31,Second Class,JH-15985,Joseph Holt,Consumer,Concord,North Carolina,...,FUR-TA-10000198,Furniture,Tables,Chromcraft Bull-Nose Wood Oval Conference Tabl...,4297.644,13,0.4,-1862.3124,865.74,Critical
10,34577,CA-2011-102988,2011-04-05,2011-04-09,Second Class,GM-14695,Greg Maxwell,Corporate,Alexandria,Virginia,...,OFF-SU-10002881,Office Supplies,Supplies,Martin Yale Chadless Opener Electric Letter Op...,4164.050,5,0.0,83.2810,846.54,High

In [ ]:
#### Q.21 Orders which has disocount between (0.2 , 0.4 )
#### Q.22 Orders with profit from 3000 - 5000 
#### Q.23 Orders with profit - 2000 - 6000 and sales between 5000 - 10000
#### Q24. Orders from copiers , machines and chairs and phones 
#### Q25. Orders from Mexico , Australia and Germany and iraq

#### Category Data Analysis 
###### unique() , nunique() , value_counts()

In [166]:
# Category - 
data['Category'].unique()   # returns all the unique elements

array(['Technology', 'Furniture', 'Office Supplies'], dtype=object)

In [168]:
data['Category'].nunique()   # number of Unique values

3

In [170]:
data['Category'].value_counts()

Category
Office Supplies    31273
Technology         10141
Furniture           9876
Name: count, dtype: int64

In [ ]:
### Q.26 cateogorical Analysis on - segment , country , sub category , city , order priority

In [174]:
data['Market'].unique()

array(['US', 'APAC', 'EU', 'Africa', 'EMEA', 'LATAM', 'Canada'],
      dtype=object)

In [176]:
data['Market'].nunique()

7

In [178]:
data['Market'].value_counts()

Market
APAC      11002
LATAM     10294
EU        10000
US         9994
EMEA       5029
Africa     4587
Canada      384
Name: count, dtype: int64

#### loc and iloc - Indexing 
- loc - Label Based Indexing
- syntax df.loc[row_index,columns_index]

- iloc - Number based indexing
- syntax - df.iloc[row_index,column_index]

In [197]:
user = pd.DataFrame({ 'ID' : [ 1,2,3,4,5,6] , 
                    'Name' : ['Amay','Sakshi','Viraj','Mohini','ravi' ,'vinita'],
                     'salary' : [ 23000,34000,12000,45000,67000,90000],
                     'age' : [ 23,24,26,19,20,21],
                     'job' : [ 'DA' , 'DS', 'MLE', 'DA','MLOPS' ,'DS'] ,
                     'city' : [ 'Pune' , 'Hyd' ,'Ban' ,'Pune' , 'Delhi' ,'Pune']})

In [193]:
user.head(2)

   ID    Name  salary  age job  city
0   1    Amay   23000   23  DA  Pune
1   2  Sakshi   34000   24  DS   Hyd

##### loc[row_start : row_stop ,column_start: column_stop]

In [212]:
user.loc[3:5]   # Row filterations

   ID    Name  salary  age    job   city
3   4  Mohini   45000   19     DA   Pune
4   5    ravi   67000   20  MLOPS  Delhi
5   6  vinita   90000   21     DS   Pune

In [229]:
user.loc[1:2,['Name','city']]

     Name city
1  Sakshi  Hyd
2   Viraj  Ban

In [217]:
user.loc[ : , 'Name']

0      Amay
1    Sakshi
2     Viraj
3    Mohini
4      ravi
5    vinita
Name: Name, dtype: object

In [ ]:
####